name: Deploy

on:
  push:
    branches:
      - master

jobs:
  check-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Packages
        run: npm install
      - name: Format Check
        run: npm run format-check
      - name: Typecheck
        run: npm run typecheck
      - name: Lint Check
        run: npm run lint
      - name: Test Build
        run: npm run build --if-present
      - uses: actions/checkout@v2
      - name: Deploy to Heroku
      - uses: akhileshns/heroku-deploy@v3.0.4
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: know-it-web
          heroku_email: rafit.jamil@gmail.com
